services:
  composer_backend:
    build: ./backend
    container_name: beat_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./shared_outputs:/app/shared_outputs
    deploy:
      resources:
        limits:
          memory: 10G # AI needs RAM

  composer_frontend:
    build: ./frontend
    container_name: beat_frontend
    restart: unless-stopped
    ports:
      - "8060:8050" # Access UI at YOUR_IP:8060
    volumes:
      - ./shared_outputs:/app/shared_outputs
    depends_on:
      - composer_backend